// generated by dlavm.backend in 2026-04-05 22:41:05

// hbm storage define
uint64_t hbm0 = 0x000000000;
uint64_t hbm1 = 0x0000000c0;
uint64_t hbm2 = 0x000067cc0;
uint64_t hbm3 = 0x000067f40;
uint64_t hbm4 = 0x000067fc0;
uint64_t hbm5 = 0x0000917c0;
// runtime storage define
uint64_t runtime0 = 0x0000918c0;
uint64_t runtime1 = 0x0000c18c0;

uint64_t raw_image_in = runtime0;

uint64_t output = runtime0;

void wall_oss_run_Mergerlnweight0_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/wall_oss_run/Merger/LN_HBM_bin/LN1_ln_wt_and_bias_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm0 + (port * 268435456))), 192);
  }
}
void wall_oss_run_Mergerhweight1_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/wall_oss_run/Merger/MVM_BN_HBM_bin/MVMBN2_wt_and_scale_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm1 + (port * 268435456))), 424960);
  }
}
void wall_oss_run_Mergerhbias1_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/wall_oss_run/Merger/MVM_BN_HBM_bin/MVMBN2_bn_wt_and_bias_in_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm2 + (port * 268435456))), 640);
  }
}
void wall_oss_run_Mergergelu_weight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 1; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/wall_oss_run/Merger/ACT_HBM_bin/ACT_parameter_in_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm3 + (port * 268435456))), 128);
  }
}
void wall_oss_run_Mergerhweight2_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/wall_oss_run/Merger/MVM_BN_HBM_bin/MVMBN3_wt_and_scale_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm4 + (port * 268435456))), 169984);
  }
}
void wall_oss_run_Mergerhbias2_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/wall_oss_run/Merger/MVM_BN_HBM_bin/MVMBN3_bn_wt_and_bias_in_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm5 + (port * 268435456))), 256);
  }
}

void test_load_params(HANDLE& h2cx, char* prefix) {
  wall_oss_run_Mergerlnweight0_load_param(h2cx, prefix);
  wall_oss_run_Mergerhweight1_load_param(h2cx, prefix);
  wall_oss_run_Mergerhbias1_load_param(h2cx, prefix);
  wall_oss_run_Mergergelu_weight_load_param(h2cx, prefix);
  wall_oss_run_Mergerhweight2_load_param(h2cx, prefix);
  wall_oss_run_Mergerhbias2_load_param(h2cx, prefix);
}

void norm_step_1(HANDLE& device, int token) {
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  for (int w = 0; w < 1; w += 1) {
    uint64_t feature_in_addr = (runtime0 + ((w * out_w_per_slice) * 32));
    uint64_t wt_base_addr = hbm0;
    uint64_t feature_out_addr = (runtime1 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, ((uint32_t)wt_base_addr));
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, ((32 * token) * 3));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, ((32 * token) * 3));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, 1280);
    CSB_Write(device, 138, 1);
    CSB_Write(device, 139, ((w < 0) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 140, 0);
    CSB_Write(device, 141, 168755);
    CSB_Write(device, 142, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 143, 66305);
    CSB_Write(device, 144, 0);
    CSB_Write(device, 145, 32);
#ifdef PRINT_STEP
    printf("start norm_step_1\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void mvm_f16xi4_step_2(HANDLE& device, int token) {
  int min_dat_depth = ((((token / 4) * 5120) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = (token / 4);
  int out_w_slice_last = (token / 4);
  if ((min_dat_depth > 1024)) {
    out_w_slice = 102;
    out_w_slice_last = (((token / 4) % out_w_slice) ? ((token / 4) % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = (((((token / 4) + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = ((((((5120 * (token / 4)) * 10) * 16) / 8192) + 1660) + 20);
  int total_clks_if_reuse_dat = (((((5120 * (token / 4)) * 16) / 8192) + ((13598720 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 10; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm1 + (42496 * ch));
        uint64_t feature_out_addr = ((runtime0 + (32 * (w * out_w_slice))) + ((32 * (token / 4)) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm2 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 5120);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 9) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 21248);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 1024);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * (token / 4)));
        CSB_Write(device, 30, (32 * (token / 4)));
        CSB_Write(device, 31, (32 * (token / 4)));
        CSB_Write(device, 32, (32 * (token / 4)));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_2\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 10; ch += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm1 + (42496 * ch));
        uint64_t feature_out_addr = ((runtime0 + (32 * (w * out_w_slice))) + ((32 * (token / 4)) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm2 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 5120);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 9) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 21248);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 1024);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * (token / 4)));
        CSB_Write(device, 30, (32 * (token / 4)));
        CSB_Write(device, 31, (32 * (token / 4)));
        CSB_Write(device, 32, (32 * (token / 4)));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_2\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void activate_step_3(HANDLE& device, int token) {
  int Wout_Split_Times_minus1 = 0;
  int out_w_in_last_slice = (token / 4);
  Wout_Split_Times_minus1 = (((((token / 4) + 102) - 1) / 102) - 1);
  out_w_in_last_slice = ((token / 4) - (Wout_Split_Times_minus1 * 102));
  for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
    uint64_t feature_in_addr = (runtime0 + ((w * 102) * 32));
    uint64_t wt_base_addr = hbm3;
    uint64_t feature_out_addr = (runtime1 + ((w * 102) * 32));
    CSB_Write(device, 130, ((uint32_t)wt_base_addr));
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, (32 * (token / 4)));
    CSB_Write(device, 133, (32 * (token / 4)));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, (32 * (token / 4)));
    CSB_Write(device, 136, (32 * (token / 4)));
    CSB_Write(device, 137, 5120);
    CSB_Write(device, 138, 1);
    CSB_Write(device, 139, ((w < Wout_Split_Times_minus1) ? 102 : out_w_in_last_slice));
    CSB_Write(device, 140, (w ? 2 : 1));
    CSB_Write(device, 141, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 142, 0);
    CSB_Write(device, 143, 0);
    CSB_Write(device, 144, 0);
    CSB_Write(device, 145, 16);
#ifdef PRINT_STEP
    printf("start activate_step_3\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void mvm_f16xi4_step_4(HANDLE& device, int token) {
  int min_dat_depth = ((((token / 4) * 5120) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = (token / 4);
  int out_w_slice_last = (token / 4);
  if ((min_dat_depth > 1024)) {
    out_w_slice = 102;
    out_w_slice_last = (((token / 4) % out_w_slice) ? ((token / 4) % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = (((((token / 4) + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = ((((((5120 * (token / 4)) * 4) * 16) / 8192) + 664) + 20);
  int total_clks_if_reuse_dat = (((((5120 * (token / 4)) * 16) / 8192) + ((5439488 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 4; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm4 + (42496 * ch));
        uint64_t feature_out_addr = ((runtime0 + (32 * (w * out_w_slice))) + ((32 * (token / 4)) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm5 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 5120);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 3) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 21248);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 1024);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * (token / 4)));
        CSB_Write(device, 30, (32 * (token / 4)));
        CSB_Write(device, 31, (32 * (token / 4)));
        CSB_Write(device, 32, (32 * (token / 4)));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_4\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 4; ch += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm4 + (42496 * ch));
        uint64_t feature_out_addr = ((runtime0 + (32 * (w * out_w_slice))) + ((32 * (token / 4)) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm5 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 5120);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 3) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 21248);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 1024);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * (token / 4)));
        CSB_Write(device, 30, (32 * (token / 4)));
        CSB_Write(device, 31, (32 * (token / 4)));
        CSB_Write(device, 32, (32 * (token / 4)));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_4\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}

void test(HANDLE& device, int token) {
  norm_step_1(device, token);
  mvm_f16xi4_step_2(device, token);
  activate_step_3(device, token);
  mvm_f16xi4_step_4(device, token);
}
