// generated by dlavm.backend in 2025-10-22 11:26:46

// hbm storage define
uint64_t hbm0 = 0x000000000;
uint64_t hbm1 = 0x000000040;
uint64_t hbm2 = 0x000009040;
uint64_t hbm3 = 0x000009240;
uint64_t hbm4 = 0x00000b640;
uint64_t hbm5 = 0x00000b6c0;
uint64_t hbm6 = 0x00000dac0;
uint64_t hbm7 = 0x00000db40;
uint64_t hbm8 = 0x000015f40;
// hbm_cache storage define
uint64_t hbm_cache0 = 0x000015f80;
uint64_t hbm_cache1 = 0x000055f80;
// runtime storage define
uint64_t runtime0 = 0x000095f80;
uint64_t runtime1 = 0x0000a5f80;
uint64_t runtime2 = 0x0000b5f80;
uint64_t runtime3 = 0x0004b5f80;

uint64_t input = runtime0;

uint64_t output = runtime3;

void whisper_attention_00_lnweight0_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00lnw0", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm0 + (port * 268435456))), 64);
  }
}
void whisper_attention_00_qweight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00qw", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm1 + (port * 268435456))), 36864);
  }
}
void whisper_attention_00_qbias_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00qb", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm2 + (port * 268435456))), 512);
  }
}
void whisper_attention_00_kweight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00kw", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm3 + (port * 268435456))), 9216);
  }
}
void whisper_attention_00_kbias_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00kb", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm4 + (port * 268435456))), 128);
  }
}
void whisper_attention_00_vweight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00vw", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm5 + (port * 268435456))), 9216);
  }
}
void whisper_attention_00_vbias_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00vb", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm6 + (port * 268435456))), 128);
  }
}
void whisper_attention_00_oweight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00ow", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm7 + (port * 268435456))), 33792);
  }
}
void whisper_attention_00_obias_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/whisper_attention_00ob", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm8 + (port * 268435456))), 64);
  }
}

void test_load_params(HANDLE& h2cx, char* prefix) {
  whisper_attention_00_lnweight0_load_param(h2cx, prefix);
  whisper_attention_00_qweight_load_param(h2cx, prefix);
  whisper_attention_00_qbias_load_param(h2cx, prefix);
  whisper_attention_00_kweight_load_param(h2cx, prefix);
  whisper_attention_00_kbias_load_param(h2cx, prefix);
  whisper_attention_00_vweight_load_param(h2cx, prefix);
  whisper_attention_00_vbias_load_param(h2cx, prefix);
  whisper_attention_00_oweight_load_param(h2cx, prefix);
  whisper_attention_00_obias_load_param(h2cx, prefix);
}

void norm_step_1(HANDLE& device, int token) {
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  for (int w = 0; w < 1; w += 1) {
    uint64_t feature_in_addr = (runtime0 + ((w * out_w_per_slice) * 32));
    uint64_t wt_base_addr = hbm0;
    uint64_t feature_out_addr = (runtime1 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, ((uint32_t)wt_base_addr));
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, (32 * token));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, (32 * token));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, 512);
    CSB_Write(device, 138, 1);
    CSB_Write(device, 139, ((w < 0) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 140, 1);
    CSB_Write(device, 141, 180224);
    CSB_Write(device, 142, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 143, 65793);
    CSB_Write(device, 144, 0);
    CSB_Write(device, 145, 32);
#ifdef PRINT_STEP
    printf("start norm_step_1\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void mvm_f16xi4_step_2(HANDLE& device, int token) {
  int min_dat_depth = (((token * 512) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = ((((((512 * token) * 4) * 16) / 8192) + 144) + 20);
  int total_clks_if_reuse_dat = (((((512 * token) * 16) / 8192) + ((1179648 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 4; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm1 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime2 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm2 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 3) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_2\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 4; ch += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm1 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime2 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm2 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 3) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_2\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void mvm_f16xi4_step_3(HANDLE& device, int token) {
  int min_dat_depth = (((token * 512) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = (((((512 * token) * 16) / 8192) + 36) + 20);
  int total_clks_if_reuse_dat = (((((512 * token) * 16) / 8192) + ((294912 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 1; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm3 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm4 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_3\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 1; ch += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm3 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm4 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_3\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void kvcache2hbm_step_4(HANDLE& device, int token, int last_token) {
  uint64_t feature_in_addr = runtime3;
  uint64_t feature_out_addr = hbm_cache0;
  CSB_Write(device, 130, (((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)));
  CSB_Write(device, 131, ((uint32_t)feature_in_addr));
  CSB_Write(device, 132, (32 * token));
  CSB_Write(device, 133, (32 * token));
  CSB_Write(device, 134, ((uint32_t)feature_out_addr));
  CSB_Write(device, 135, 16384);
  CSB_Write(device, 136, 4096);
  CSB_Write(device, 137, 128);
  CSB_Write(device, 138, 1);
  CSB_Write(device, 139, token);
  CSB_Write(device, 140, 8);
  CSB_Write(device, 141, last_token);
  CSB_Write(device, 142, 1);
  CSB_Write(device, 143, 516);
  CSB_Write(device, 144, 0);
  CSB_Write(device, 145, 64);
#ifdef PRINT_STEP
  printf("start kvcache2hbm_step_4\n");
#endif
  while (CSB_Read(device, 129) != 1) {}
}
void mvm_f16xf16_step_5(HANDLE& device, int token, int last_token) {
  int min_dat_depth = ((token * 8192) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int out_ch_slice = ((1024 < (((((token + last_token) + 32) - 1) / 32) * 32)) ? 1024 : (((((token + last_token) + 32) - 1) / 32) * 32));
  int CHout_Split_Times = ((out_ch_slice < (((((token + last_token) + 32) - 1) / 32) * 32)) ? ((((((((token + last_token) + 32) - 1) / 32) * 32) + out_ch_slice) - 1) / out_ch_slice) : 1);
  int out_ch_slice_last = (((((((token + last_token) + 32) - 1) / 32) * 32) % out_ch_slice) ? ((((((token + last_token) + 32) - 1) / 32) * 32) % out_ch_slice) : out_ch_slice);
  int total_clks_if_reuse_wt = (((((8192 * token) * ((CHout_Split_Times - 1) + 1)) / 8192) + 4) + 20);
  int total_clks_if_reuse_dat = ((((8192 * token) / 8192) + ((32768 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);

  // for cmd debug
  printf("out_ch_slice is %d\n", out_ch_slice);
  printf("CHout_Split_Times is %d\n", CHout_Split_Times);
  printf("Wout_Split_Times_minus1 is %d\n", Wout_Split_Times_minus1);
  printf("out_w_slice is %d\n", out_w_slice);
  printf("total_clks_if_reuse_wt is %d\n", total_clks_if_reuse_wt);
  printf("total_clks_if_reuse_dat is %d\n", total_clks_if_reuse_dat);
  FILE *cmd_comapare_log;
  if ((cmd_comapare_log = fopen("cmd_comapare_log.log", "wb")) == NULL)  
    printf("cannot open file: %s !\n", "cmd_comapare_log.log");
  int times = 1;
  
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int h = 0; h < 8; h += 1) {
      for (int ch = 0; ch < ((CHout_Split_Times - 1) + 1); ch += 1) {
        for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
          uint64_t feature_in_addr = ((runtime2 + (32 * (w * out_w_slice))) + (h * (32 * token)));
          uint64_t wt_base_addr = ((hbm_cache0 + (((256 * ch) * out_ch_slice) / 32)) + (h * 16384));
          uint64_t feature_out_addr = (((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * out_w_slice) / 512))) + (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          CSB_Write(device, 2, 128);
          CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 4, 4);
          CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 6, 1);
          CSB_Write(device, 7, ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          CSB_Write(device, 8, (ch * out_ch_slice));
          CSB_Write(device, 9, 0);
          CSB_Write(device, 10, ((uint32_t)feature_in_addr));
          CSB_Write(device, 11, ((uint32_t)wt_base_addr));
          CSB_Write(device, 12, 2048);
          CSB_Write(device, 13, ((uint32_t)feature_out_addr));
          CSB_Write(device, 14, 0);
          CSB_Write(device, 15, 0);
          CSB_Write(device, 16, (w ? 1 : 0));
          CSB_Write(device, 17, 3);
          CSB_Write(device, 18, 229376);
          CSB_Write(device, 19, 65792);
          CSB_Write(device, 20, 65792);
          CSB_Write(device, 21, 0);
          CSB_Write(device, 22, 0);
          CSB_Write(device, 23, 0);
          CSB_Write(device, 24, 0);
          CSB_Write(device, 25, 0);
          CSB_Write(device, 26, 0);
          CSB_Write(device, 27, 260);
          CSB_Write(device, 28, 1);
          CSB_Write(device, 29, (32 * token));
          CSB_Write(device, 30, (32 * token));
          CSB_Write(device, 31, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          CSB_Write(device, 32, (32 * token));
          CSB_Write(device, 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          CSB_Write(device, 34, 15);

          // for cmd debug
          fprintf(cmd_comapare_log, "reg %d is %d\n", 2,  128);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 3,  ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 4,  4);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 5,  ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 6,  1);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 7,  ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 8,  (ch * out_ch_slice));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 9,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 10, ((uint32_t)feature_in_addr)-runtime2);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 11, ((uint32_t)wt_base_addr)-hbm_cache0+384000);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 12, 2048);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 13, ((uint32_t)feature_out_addr)-runtime3+646144);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 14, 0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 15, 0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 16, (w ? 1 : 0));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 17, 3);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 18, 229376);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 19, 65792);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 20, 65792);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 21, 0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 22, 0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 23, 0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 24, 0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 25, 0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 26, 0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 27, 260);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 28, 1);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 29, (32 * token));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 30, (32 * token));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 31, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 32, (32 * token));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          fprintf(cmd_comapare_log, "reg %d is %d\n\n\n", 34, 15);
#ifdef PRINT_STEP
          printf("start mvm_f16xf16_step_5\n");
#endif
          while (CSB_Read(device, 1) != 1) {}
        }
      }
    }
  } else {
    for (int h = 0; h < 8; h += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        for (int ch = 0; ch < ((CHout_Split_Times - 1) + 1); ch += 1) {
          uint64_t feature_in_addr = ((runtime2 + (32 * (w * out_w_slice))) + (h * (32 * token)));
          uint64_t wt_base_addr = ((hbm_cache0 + (((256 * ch) * out_ch_slice) / 32)) + (h * 16384));
          uint64_t feature_out_addr = (((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * out_w_slice) / 512))) + (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          CSB_Write(device, 2, 128);
          CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 4, 4);
          CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 6, 1);
          CSB_Write(device, 7, ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          CSB_Write(device, 8, (ch * out_ch_slice));
          CSB_Write(device, 9, 0);
          CSB_Write(device, 10, ((uint32_t)feature_in_addr));
          CSB_Write(device, 11, ((uint32_t)wt_base_addr));
          CSB_Write(device, 12, 2048);
          CSB_Write(device, 13, ((uint32_t)feature_out_addr));
          CSB_Write(device, 14, 0);
          CSB_Write(device, 15, 0);
          CSB_Write(device, 16, ((ch ? 1 : 0) * 2));
          CSB_Write(device, 17, 3);
          CSB_Write(device, 18, 229376);
          CSB_Write(device, 19, 65792);
          CSB_Write(device, 20, 65792);
          CSB_Write(device, 21, 0);
          CSB_Write(device, 22, 0);
          CSB_Write(device, 23, 0);
          CSB_Write(device, 24, 0);
          CSB_Write(device, 25, 0);
          CSB_Write(device, 26, 0);
          CSB_Write(device, 27, 260);
          CSB_Write(device, 28, 1);
          CSB_Write(device, 29, (32 * token));
          CSB_Write(device, 30, (32 * token));
          CSB_Write(device, 31, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          CSB_Write(device, 32, (32 * token));
          CSB_Write(device, 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          CSB_Write(device, 34, 15);

          // for cmd debug
          fprintf(cmd_comapare_log, "run mvm_f16xf16_step_5 the %d times.\n", times);
          fprintf(cmd_comapare_log, "w offset=%lu, ch offset=%lu, h offset=%lu.\n", (32 * (w * out_w_slice)), ((32 * token) * ((ch * out_w_slice) / 512)), (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 2,   128);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 3,   ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 4,   4);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 5,   ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 6,   1);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 7,   ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 8,   (ch * out_ch_slice));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 9,   0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 10, ((uint32_t)feature_in_addr)-runtime2);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 11, ((uint32_t)wt_base_addr)-hbm_cache0+384000);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 12, 2048);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 13, ((uint32_t)feature_out_addr)-runtime3+646144);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 14,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 15,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 16,  ((ch ? 1 : 0) * 2));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 17,  3);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 18,  229376);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 19,  65792);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 20,  65792);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 21,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 22,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 23,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 24,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 25,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 26,  0);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 27,  260);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 28,  1);
          fprintf(cmd_comapare_log, "reg %d is %d\n", 29,  (32 * token));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 30,  (32 * token));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 31,  ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 32,  (32 * token));
          fprintf(cmd_comapare_log, "reg %d is %d\n", 33,  ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          fprintf(cmd_comapare_log, "reg %d is %d\n\n\n", 34,  15);
          times = times + 1;
#ifdef PRINT_STEP
          printf("start mvm_f16xf16_step_5\n");
#endif
          while (CSB_Read(device, 1) != 1) {}
        }
      }
    }
  }
}
void softmax_step_6(HANDLE& device, int token, int last_token) {
  int Wout_Split_Times_minus1 = 0;
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  if (((4096 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512)) > 8388608)) {
    Wout_Split_Times_minus1 = ((((token + (8388608 / ((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16))) - 1) / (8388608 / ((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16))) - 1);
    out_w_per_slice = (8388608 / ((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16));
    out_w_in_last_slice = (token - (Wout_Split_Times_minus1 * out_w_per_slice));
  }
  for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
    uint64_t feature_in_addr = (runtime3 + ((w * out_w_per_slice) * 32));
    uint64_t feature_out_addr = (runtime2 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, (((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)));
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, (token + last_token));
    CSB_Write(device, 138, 8);
    CSB_Write(device, 139, (token + last_token));
    CSB_Write(device, 140, ((w < Wout_Split_Times_minus1) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 141, ((w * out_w_per_slice) + ((token + last_token) - token)));
    // CSB_Write(device, 142, ((token > 1) ? 1 : 0));
    CSB_Write(device, 142, 0);
    CSB_Write(device, 143, 0);
    CSB_Write(device, 144, 0);
    CSB_Write(device, 145, 8);
#ifdef PRINT_STEP
    printf("start softmax_step_6\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void mvm_f16xi4_step_7(HANDLE& device, int token) {
  int min_dat_depth = (((token * 512) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = (((((512 * token) * 16) / 8192) + 36) + 20);
  int total_clks_if_reuse_dat = (((((512 * token) * 16) / 8192) + ((294912 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 1; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm5 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm6 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_7\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 1; ch += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm5 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm6 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_7\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void kvcache2hbm_step_8(HANDLE& device, int token, int last_token) {
  uint64_t feature_in_addr = runtime3;
  uint64_t feature_out_addr = hbm_cache1;
  CSB_Write(device, 130, (((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)));
  CSB_Write(device, 131, ((uint32_t)feature_in_addr));
  CSB_Write(device, 132, (32 * token));
  CSB_Write(device, 133, (32 * token));
  CSB_Write(device, 134, ((uint32_t)feature_out_addr));
  CSB_Write(device, 135, 16384);
  CSB_Write(device, 136, 4096);
  CSB_Write(device, 137, 128);
  CSB_Write(device, 138, 1);
  CSB_Write(device, 139, token);
  CSB_Write(device, 140, 8);
  CSB_Write(device, 141, last_token);
  CSB_Write(device, 142, 2);
  CSB_Write(device, 143, 516);
  CSB_Write(device, 144, 0);
  CSB_Write(device, 145, 64);
#ifdef PRINT_STEP
  printf("start kvcache2hbm_step_8\n");
#endif
  while (CSB_Read(device, 129) != 1) {}
}
void mvm_f16xf16_step_9(HANDLE& device, int token, int last_token) {
  int min_dat_depth = ((token * (((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16) * 8)) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = (8388608 / (((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16) * 8));
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int tp_log_out_ch_slice = (1 << ((int)(log2(((16777216 / ((32 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16)) * 32)))));
  int tp_out_ch_slice = ((tp_log_out_ch_slice > ((16777216 / ((32 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16)) * 32)) ? (tp_log_out_ch_slice / 2) : tp_log_out_ch_slice);
  int out_ch_slice = ((((tp_out_ch_slice > 1024) ? 1024 : tp_out_ch_slice) < 128) ? ((tp_out_ch_slice > 1024) ? 1024 : tp_out_ch_slice) : 128);
  int CHout_Split_Times = ((out_ch_slice < 128) ? (((128 + out_ch_slice) - 1) / out_ch_slice) : 1);
  int out_ch_slice_last = ((128 % out_ch_slice) ? (128 % out_ch_slice) : out_ch_slice);
  int total_clks_if_reuse_wt = ((((((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 8192) * token) * ((CHout_Split_Times - 1) + 1)) / 8192) + ((((128 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16) / 8) / 8192)) + 20);
  int total_clks_if_reuse_dat = (((((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 8192) * token) / 8192) + (((((128 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16) / 8) * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int h = 0; h < 8; h += 1) {
      for (int ch = 0; ch < ((CHout_Split_Times - 1) + 1); ch += 1) {
        for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
          uint64_t feature_in_addr = ((runtime2 + (32 * (w * out_w_slice))) + (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          uint64_t wt_base_addr = ((hbm_cache1 + (((4096 * ch) * out_ch_slice) / 32)) + (h * 16384));
          uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((h * (32 * token)) / 1));
          CSB_Write(device, 2, (((((token + last_token) + 32) - 1) / 32) * 32));
          CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 4, 1);
          CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 6, 1);
          CSB_Write(device, 7, ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          CSB_Write(device, 8, (ch * out_ch_slice));
          CSB_Write(device, 9, 128);
          CSB_Write(device, 10, ((uint32_t)feature_in_addr));
          CSB_Write(device, 11, ((uint32_t)wt_base_addr));
          CSB_Write(device, 12, (((((128 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16) / 8) / 128) * 8));
          CSB_Write(device, 13, ((uint32_t)feature_out_addr));
          CSB_Write(device, 14, 0);
          CSB_Write(device, 15, 0);
          CSB_Write(device, 16, (w ? 1 : 0));
          CSB_Write(device, 17, 4);
          CSB_Write(device, 18, 224577);
          CSB_Write(device, 19, 65792);
          CSB_Write(device, 20, 65792);
          CSB_Write(device, 21, 0);
          CSB_Write(device, 22, 0);
          CSB_Write(device, 23, 0);
          CSB_Write(device, 24, 0);
          CSB_Write(device, 25, 0);
          CSB_Write(device, 26, 4096);
          CSB_Write(device, 27, 260);
          CSB_Write(device, 28, 2);
          CSB_Write(device, 29, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          CSB_Write(device, 30, (32 * token));
          CSB_Write(device, 31, (32 * token));
          CSB_Write(device, 32, (32 * token));
          CSB_Write(device, 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          CSB_Write(device, 34, 15);
#ifdef PRINT_STEP
          printf("start mvm_f16xf16_step_9\n");
#endif
          while (CSB_Read(device, 1) != 1) {}
        }
      }
    }
  } else {
    for (int h = 0; h < 8; h += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        for (int ch = 0; ch < ((CHout_Split_Times - 1) + 1); ch += 1) {
          uint64_t feature_in_addr = ((runtime2 + (32 * (w * out_w_slice))) + (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          uint64_t wt_base_addr = ((hbm_cache1 + (((4096 * ch) * out_ch_slice) / 32)) + (h * 16384));
          uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((h * (32 * token)) / 1));
          CSB_Write(device, 2, (((((token + last_token) + 32) - 1) / 32) * 32));
          CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 4, 1);
          CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 6, 1);
          CSB_Write(device, 7, ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          CSB_Write(device, 8, (ch * out_ch_slice));
          CSB_Write(device, 9, 128);
          CSB_Write(device, 10, ((uint32_t)feature_in_addr));
          CSB_Write(device, 11, ((uint32_t)wt_base_addr));
          CSB_Write(device, 12, (((((128 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16) / 8) / 128) * 8));
          CSB_Write(device, 13, ((uint32_t)feature_out_addr));
          CSB_Write(device, 14, 0);
          CSB_Write(device, 15, 0);
          CSB_Write(device, 16, ((ch ? 1 : 0) * 2));
          CSB_Write(device, 17, 4);
          CSB_Write(device, 18, 224577);
          CSB_Write(device, 19, 65792);
          CSB_Write(device, 20, 65792);
          CSB_Write(device, 21, 0);
          CSB_Write(device, 22, 0);
          CSB_Write(device, 23, 0);
          CSB_Write(device, 24, 0);
          CSB_Write(device, 25, 0);
          CSB_Write(device, 26, 4096);
          CSB_Write(device, 27, 260);
          CSB_Write(device, 28, 2);
          CSB_Write(device, 29, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          CSB_Write(device, 30, (32 * token));
          CSB_Write(device, 31, (32 * token));
          CSB_Write(device, 32, (32 * token));
          CSB_Write(device, 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          CSB_Write(device, 34, 15);
#ifdef PRINT_STEP
          printf("start mvm_f16xf16_step_9\n");
#endif
          while (CSB_Read(device, 1) != 1) {}
        }
      }
    }
  }
}
void mvm_f16xi4_step_10(HANDLE& device, int token) {
  int min_dat_depth = (((token * 4096) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 128;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = (((((4096 * token) * 16) / 8192) + 132) + 20);
  int total_clks_if_reuse_dat = (((((4096 * token) * 16) / 8192) + ((1081344 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 1; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime3 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm7 + (33792 * ch));
        uint64_t feature_out_addr = ((runtime1 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm8 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 4096);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 16896);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 2048);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_10\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 1; ch += 1) {
        uint64_t feature_in_addr = (runtime3 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm7 + (33792 * ch));
        uint64_t feature_out_addr = ((runtime1 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm8 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 4096);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 16896);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 2048);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_10\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void elementwise_step_11(HANDLE& device, int token) {
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  for (int w = 0; w < 1; w += 1) {
    uint64_t feature_in_addr = (runtime1 + ((w * out_w_per_slice) * 32));
    uint64_t wt_base_addr = (runtime0 + ((w * out_w_per_slice) * 32));
    uint64_t feature_out_addr = (runtime3 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, 0);
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, (32 * token));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, (32 * token));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, 512);
    CSB_Write(device, 138, ((w < 0) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 139, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 140, ((uint32_t)wt_base_addr));
    CSB_Write(device, 141, (32 * token));
    CSB_Write(device, 142, (32 * token));
    CSB_Write(device, 145, 2);
#ifdef PRINT_STEP
    printf("start elementwise_step_11\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}

void test(HANDLE& device, int token, int last_token) {
  norm_step_1(device, token);
  mvm_f16xi4_step_2(device, token);
  mvm_f16xi4_step_3(device, token);
  kvcache2hbm_step_4(device, token, last_token);
  mvm_f16xf16_step_5(device, token, last_token);
  softmax_step_6(device, token, last_token);
  mvm_f16xi4_step_7(device, token);
  kvcache2hbm_step_8(device, token, last_token);
  mvm_f16xf16_step_9(device, token, last_token);
  mvm_f16xi4_step_10(device, token);
  elementwise_step_11(device, token);
}


void trp_cmd(HANDLE& device)
{
  int addr = 129;
  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,0);
  CSB_Write(device,11,384000);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,646144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,0);
  CSB_Write(device,11,392192);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,742144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,32768);
  CSB_Write(device,11,384000);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,678912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,32768);
  CSB_Write(device,11,392192);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,774912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,48000);
  CSB_Write(device,11,416768);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,790144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,48000);
  CSB_Write(device,11,424960);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,886144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,80768);
  CSB_Write(device,11,416768);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,822912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,80768);
  CSB_Write(device,11,424960);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,918912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,96000);
  CSB_Write(device,11,449536);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,934144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,96000);
  CSB_Write(device,11,457728);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1030144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,128768);
  CSB_Write(device,11,449536);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,966912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,128768);
  CSB_Write(device,11,457728);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1062912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,144000);
  CSB_Write(device,11,482304);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1078144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,144000);
  CSB_Write(device,11,490496);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1174144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,176768);
  CSB_Write(device,11,482304);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1110912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,176768);
  CSB_Write(device,11,490496);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1206912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,192000);
  CSB_Write(device,11,515072);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1222144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,192000);
  CSB_Write(device,11,523264);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1318144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,224768);
  CSB_Write(device,11,515072);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1254912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,224768);
  CSB_Write(device,11,523264);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1350912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,240000);
  CSB_Write(device,11,547840);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1366144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,240000);
  CSB_Write(device,11,556032);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1462144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,272768);
  CSB_Write(device,11,547840);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1398912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,272768);
  CSB_Write(device,11,556032);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1494912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,288000);
  CSB_Write(device,11,580608);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1510144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,288000);
  CSB_Write(device,11,588800);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1606144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,320768);
  CSB_Write(device,11,580608);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1542912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,320768);
  CSB_Write(device,11,588800);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1638912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,336000);
  CSB_Write(device,11,613376);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1654144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,1024);
  CSB_Write(device,4,4);
  CSB_Write(device,5,1024);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,336000);
  CSB_Write(device,11,621568);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1750144);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,1024);
  CSB_Write(device,8,0);
  CSB_Write(device,9,0);
  CSB_Write(device,10,368768);
  CSB_Write(device,11,613376);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1686912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,0);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}

  CSB_Write(device,2,128);
  CSB_Write(device,3,476);
  CSB_Write(device,4,4);
  CSB_Write(device,5,476);
  CSB_Write(device,6,1);
  CSB_Write(device,7,480);
  CSB_Write(device,8,1024);
  CSB_Write(device,9,0);
  CSB_Write(device,10,368768);
  CSB_Write(device,11,621568);
  CSB_Write(device,12,2048);
  CSB_Write(device,13,1782912);
  CSB_Write(device,14,0);
  CSB_Write(device,15,0);
  CSB_Write(device,16,2);
  CSB_Write(device,17,3);
  CSB_Write(device,18,229376);
  CSB_Write(device,19,65792);
  CSB_Write(device,20,65792);
  CSB_Write(device,21,0);
  CSB_Write(device,22,0);
  CSB_Write(device,23,0);
  CSB_Write(device,24,0);
  CSB_Write(device,25,0);
  CSB_Write(device,26,0);
  CSB_Write(device,27,260);
  CSB_Write(device,28,1);
  CSB_Write(device,29,48000);
  CSB_Write(device,30,48000);
  CSB_Write(device,31,144000);
  CSB_Write(device,32,48000);
  CSB_Write(device,33,0);
  CSB_Write(device,34,15);
  while (CSB_Read(device, addr) != 1) {}
}