// generated by dlavm.backend in 2025-12-01 17:11:27

// hbm storage define
uint64_t hbm0 = 0x000000000;
uint64_t hbm1 = 0x000000040;
uint64_t hbm2 = 0x000009040;
uint64_t hbm3 = 0x000009240;
uint64_t hbm4 = 0x00000b640;
uint64_t hbm5 = 0x00000b6c0;
uint64_t hbm6 = 0x00000dac0;
uint64_t hbm7 = 0x00000db40;
uint64_t hbm8 = 0x000015f40;
uint64_t hbm9 = 0x000015f80;
uint64_t hbm10 = 0x000015fc0;
uint64_t hbm11 = 0x00001a7c0;
uint64_t hbm12 = 0x00001a8c0;
uint64_t hbm13 = 0x00001a940;
uint64_t hbm14 = 0x00001eb40;
// hbm_cache storage define
uint64_t hbm_cache0 = 0x00001eb80;
uint64_t hbm_cache1 = 0x00003eb80;
// runtime storage define
uint64_t runtime0 = 0x00005eb80;
uint64_t runtime1 = 0x00009eb80;
uint64_t runtime2 = 0x0000aeb80;
uint64_t runtime3 = 0x0004aeb80;

uint64_t input = runtime0;

uint64_t output = runtime0;

void BLOCK00_lnweight0_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00lnw0", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm0 + (port * 268435456))), 64);
  }
}
void BLOCK00_qweight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00qw", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm1 + (port * 268435456))), 36864);
  }
}
void BLOCK00_qbias_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00qb", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm2 + (port * 268435456))), 512);
  }
}
void BLOCK00_kweight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00kw", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm3 + (port * 268435456))), 9216);
  }
}
void BLOCK00_kbias_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00kb", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm4 + (port * 268435456))), 128);
  }
}
void BLOCK00_vweight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00vw", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm5 + (port * 268435456))), 9216);
  }
}
void BLOCK00_vbias_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00vb", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm6 + (port * 268435456))), 128);
  }
}
void BLOCK00_oweight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00ow", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm7 + (port * 268435456))), 33792);
  }
}
void BLOCK00_obias_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00ob", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm8 + (port * 268435456))), 64);
  }
}
void BLOCK00_lnweight1_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00/LN_HBM_bin/LN1_ln_wt_and_bias_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm9 + (port * 268435456))), 64);
  }
}
void BLOCK00_hweight1_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00/MVM_BN_HBM_bin/MVMBN2_wt_and_scale_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm10 + (port * 268435456))), 18432);
  }
}
void BLOCK00_hbias1_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00/MVM_BN_HBM_bin/MVMBN2_bn_wt_and_bias_in_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm11 + (port * 268435456))), 256);
  }
}
void BLOCK_other_silu_weight_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 1; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK_other/ACT_HBM_bin/ACT_parameter_in_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm12 + (port * 268435456))), 128);
  }
}
void BLOCK00_hweight2_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00/MVM_BN_HBM_bin/MVMBN3_wt_and_scale_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm13 + (port * 268435456))), 16896);
  }
}
void BLOCK00_hbias2_load_param(HANDLE& h2cx, char* prefix) {
  for (uint64_t port = 0; port < 32; port += 1) {
    char real_path[100];
    sprintf(real_path, "%s/BLOCK00/MVM_BN_HBM_bin/MVMBN3_bn_wt_and_bias_in_HBM_%02llu.bin", prefix, port);
    DDR_Write_bin(h2cx, real_path, ((uint64_t)(hbm14 + (port * 268435456))), 64);
  }
}

void test_load_params(HANDLE& h2cx, char* prefix) {
  BLOCK00_lnweight0_load_param(h2cx, prefix);
  BLOCK00_qweight_load_param(h2cx, prefix);
  BLOCK00_qbias_load_param(h2cx, prefix);
  BLOCK00_kweight_load_param(h2cx, prefix);
  BLOCK00_kbias_load_param(h2cx, prefix);
  BLOCK00_vweight_load_param(h2cx, prefix);
  BLOCK00_vbias_load_param(h2cx, prefix);
  BLOCK00_oweight_load_param(h2cx, prefix);
  BLOCK00_obias_load_param(h2cx, prefix);
  BLOCK00_lnweight1_load_param(h2cx, prefix);
  BLOCK00_hweight1_load_param(h2cx, prefix);
  BLOCK00_hbias1_load_param(h2cx, prefix);
  BLOCK_other_silu_weight_load_param(h2cx, prefix);
  BLOCK00_hweight2_load_param(h2cx, prefix);
  BLOCK00_hbias2_load_param(h2cx, prefix);
}

void norm_step_1(HANDLE& device, int token) {
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  for (int w = 0; w < 1; w += 1) {
    uint64_t feature_in_addr = (runtime0 + ((w * out_w_per_slice) * 32));
    uint64_t wt_base_addr = hbm0;
    uint64_t feature_out_addr = (runtime1 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, ((uint32_t)wt_base_addr));
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, (32 * token));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, (32 * token));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, 512);
    CSB_Write(device, 138, 1);
    CSB_Write(device, 139, ((w < 0) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 140, 1);
    CSB_Write(device, 141, 180224);
    CSB_Write(device, 142, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 143, 65793);
    CSB_Write(device, 144, 0);
    CSB_Write(device, 145, 32);
#ifdef PRINT_STEP
    printf("start norm_step_1\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void mvm_f16xi4_step_2(HANDLE& device, int token) {
  int min_dat_depth = (((token * 512) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = ((((((512 * token) * 4) * 16) / 8192) + 144) + 20);
  int total_clks_if_reuse_dat = (((((512 * token) * 16) / 8192) + ((1179648 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 4; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm1 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime2 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm2 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 3) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_2\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 4; ch += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm1 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime2 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm2 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 3) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_2\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void mvm_f16xi4_step_3(HANDLE& device, int token) {
  int min_dat_depth = (((token * 512) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = (((((512 * token) * 16) / 8192) + 36) + 20);
  int total_clks_if_reuse_dat = (((((512 * token) * 16) / 8192) + ((294912 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 1; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm3 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm4 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_3\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 1; ch += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm3 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm4 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_3\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void kvcache2hbm_step_4(HANDLE& device, int token, int last_token) {
  uint64_t feature_in_addr = runtime3;
  uint64_t feature_out_addr = hbm_cache0;
  CSB_Write(device, 130, (((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)));
  CSB_Write(device, 131, ((uint32_t)feature_in_addr));
  CSB_Write(device, 132, (32 * token));
  CSB_Write(device, 133, (32 * token));
  CSB_Write(device, 134, ((uint32_t)feature_out_addr));
  CSB_Write(device, 135, 16384);
  CSB_Write(device, 136, 4096);
  CSB_Write(device, 137, 128);
  CSB_Write(device, 138, 1);
  CSB_Write(device, 139, token);
  CSB_Write(device, 140, 8);
  CSB_Write(device, 141, last_token);
  CSB_Write(device, 142, 1);
  CSB_Write(device, 143, 516);
  CSB_Write(device, 144, 0);
  CSB_Write(device, 145, 64);
#ifdef PRINT_STEP
  printf("start kvcache2hbm_step_4\n");
#endif
  while (CSB_Read(device, 129) != 1) {}
}
void mvm_f16xf16_step_5(HANDLE& device, int token, int last_token) {
  int min_dat_depth = ((token * 8192) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int out_ch_slice = ((1024 < (((((token + last_token) + 32) - 1) / 32) * 32)) ? 1024 : (((((token + last_token) + 32) - 1) / 32) * 32));
  int CHout_Split_Times = ((out_ch_slice < (((((token + last_token) + 32) - 1) / 32) * 32)) ? ((((((((token + last_token) + 32) - 1) / 32) * 32) + out_ch_slice) - 1) / out_ch_slice) : 1);
  int out_ch_slice_last = (((((((token + last_token) + 32) - 1) / 32) * 32) % out_ch_slice) ? ((((((token + last_token) + 32) - 1) / 32) * 32) % out_ch_slice) : out_ch_slice);
  int total_clks_if_reuse_wt = (((((8192 * token) * ((CHout_Split_Times - 1) + 1)) / 8192) + 4) + 20);
  int total_clks_if_reuse_dat = ((((8192 * token) / 8192) + ((32768 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int h = 0; h < 8; h += 1) {
      for (int ch = 0; ch < ((CHout_Split_Times - 1) + 1); ch += 1) {
        for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
          uint64_t feature_in_addr = ((runtime2 + (32 * (w * out_w_slice))) + (h * (32 * token)));
          uint64_t wt_base_addr = ((hbm_cache0 + (((256 * ch) * out_ch_slice) / 32)) + (h * 16384));
          uint64_t feature_out_addr = (((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * out_ch_slice) / 512))) + (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          CSB_Write(device, 2, 128);
          CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 4, 4);
          CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 6, 1);
          CSB_Write(device, 7, ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          CSB_Write(device, 8, (ch * out_ch_slice));
          CSB_Write(device, 9, 0);
          CSB_Write(device, 10, ((uint32_t)feature_in_addr));
          CSB_Write(device, 11, ((uint32_t)wt_base_addr));
          CSB_Write(device, 12, 2048);
          CSB_Write(device, 13, ((uint32_t)feature_out_addr));
          CSB_Write(device, 14, 0);
          CSB_Write(device, 15, 0);
          CSB_Write(device, 16, (w ? 1 : 0));
          CSB_Write(device, 17, 3);
          CSB_Write(device, 18, 229376);
          CSB_Write(device, 19, 65792);
          CSB_Write(device, 20, 65792);
          CSB_Write(device, 21, 0);
          CSB_Write(device, 22, 0);
          CSB_Write(device, 23, 0);
          CSB_Write(device, 24, 0);
          CSB_Write(device, 25, 0);
          CSB_Write(device, 26, 0);
          CSB_Write(device, 27, 260);
          CSB_Write(device, 28, 1);
          CSB_Write(device, 29, (32 * token));
          CSB_Write(device, 30, (32 * token));
          CSB_Write(device, 31, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          CSB_Write(device, 32, (32 * token));
          CSB_Write(device, 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          CSB_Write(device, 34, 15);
#ifdef PRINT_STEP
          printf("start mvm_f16xf16_step_5\n");
#endif
          while (CSB_Read(device, 1) != 1) {}
        }
      }
    }
  } else {
    for (int h = 0; h < 8; h += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        for (int ch = 0; ch < ((CHout_Split_Times - 1) + 1); ch += 1) {
          uint64_t feature_in_addr = ((runtime2 + (32 * (w * out_w_slice))) + (h * (32 * token)));
          uint64_t wt_base_addr = ((hbm_cache0 + (((256 * ch) * out_ch_slice) / 32)) + (h * 16384));
          uint64_t feature_out_addr = (((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * out_ch_slice) / 512))) + (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          CSB_Write(device, 2, 128);
          CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 4, 4);
          CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 6, 1);
          CSB_Write(device, 7, ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          CSB_Write(device, 8, (ch * out_ch_slice));
          CSB_Write(device, 9, 0);
          CSB_Write(device, 10, ((uint32_t)feature_in_addr));
          CSB_Write(device, 11, ((uint32_t)wt_base_addr));
          CSB_Write(device, 12, 2048);
          CSB_Write(device, 13, ((uint32_t)feature_out_addr));
          CSB_Write(device, 14, 0);
          CSB_Write(device, 15, 0);
          CSB_Write(device, 16, ((ch ? 1 : 0) * 2));
          CSB_Write(device, 17, 3);
          CSB_Write(device, 18, 229376);
          CSB_Write(device, 19, 65792);
          CSB_Write(device, 20, 65792);
          CSB_Write(device, 21, 0);
          CSB_Write(device, 22, 0);
          CSB_Write(device, 23, 0);
          CSB_Write(device, 24, 0);
          CSB_Write(device, 25, 0);
          CSB_Write(device, 26, 0);
          CSB_Write(device, 27, 260);
          CSB_Write(device, 28, 1);
          CSB_Write(device, 29, (32 * token));
          CSB_Write(device, 30, (32 * token));
          CSB_Write(device, 31, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          CSB_Write(device, 32, (32 * token));
          CSB_Write(device, 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          CSB_Write(device, 34, 15);
#ifdef PRINT_STEP
          printf("start mvm_f16xf16_step_5\n");
#endif
          while (CSB_Read(device, 1) != 1) {}
        }
      }
    }
  }
}
void softmax_step_6(HANDLE& device, int token, int last_token) {
  int Wout_Split_Times_minus1 = 0;
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  if (((4096 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512)) > 8388608)) {
    Wout_Split_Times_minus1 = ((((token + (8388608 / ((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16))) - 1) / (8388608 / ((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16))) - 1);
    out_w_per_slice = (8388608 / ((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16));
    out_w_in_last_slice = (token - (Wout_Split_Times_minus1 * out_w_per_slice));
  }
  for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
    uint64_t feature_in_addr = (runtime3 + ((w * out_w_per_slice) * 32));
    uint64_t feature_out_addr = (runtime2 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, (((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)));
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, (token + last_token));
    CSB_Write(device, 138, 8);
    CSB_Write(device, 139, (token + last_token));
    CSB_Write(device, 140, ((w < Wout_Split_Times_minus1) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 141, ((w * out_w_per_slice) + ((token + last_token) - token)));
    CSB_Write(device, 142, 0);
    CSB_Write(device, 143, 0);
    CSB_Write(device, 144, 0);
    CSB_Write(device, 145, 8);
#ifdef PRINT_STEP
    printf("start softmax_step_6\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void mvm_f16xi4_step_7(HANDLE& device, int token) {
  int min_dat_depth = (((token * 512) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = (((((512 * token) * 16) / 8192) + 36) + 20);
  int total_clks_if_reuse_dat = (((((512 * token) * 16) / 8192) + ((294912 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 1; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm5 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm6 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_7\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 1; ch += 1) {
        uint64_t feature_in_addr = (runtime1 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm5 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm6 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_7\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void kvcache2hbm_step_8(HANDLE& device, int token, int last_token) {
  uint64_t feature_in_addr = runtime3;
  uint64_t feature_out_addr = hbm_cache1;
  CSB_Write(device, 130, (((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)));
  CSB_Write(device, 131, ((uint32_t)feature_in_addr));
  CSB_Write(device, 132, (32 * token));
  CSB_Write(device, 133, (32 * token));
  CSB_Write(device, 134, ((uint32_t)feature_out_addr));
  CSB_Write(device, 135, 16384);
  CSB_Write(device, 136, 4096);
  CSB_Write(device, 137, 128);
  CSB_Write(device, 138, 1);
  CSB_Write(device, 139, token);
  CSB_Write(device, 140, 8);
  CSB_Write(device, 141, last_token);
  CSB_Write(device, 142, 2);
  CSB_Write(device, 143, 516);
  CSB_Write(device, 144, 0);
  CSB_Write(device, 145, 64);
#ifdef PRINT_STEP
  printf("start kvcache2hbm_step_8\n");
#endif
  while (CSB_Read(device, 129) != 1) {}
}
void mvm_f16xf16_step_9(HANDLE& device, int token, int last_token) {
  int min_dat_depth = ((token * (((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16) * 8)) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = (8388608 / (((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 512) * 16) * 8));
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int tp_log_out_ch_slice = (1 << ((int)(log2(((16777216 / ((32 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16)) * 32)))));
  int tp_out_ch_slice = ((tp_log_out_ch_slice > ((16777216 / ((32 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16)) * 32)) ? (tp_log_out_ch_slice / 2) : tp_log_out_ch_slice);
  int out_ch_slice = ((((tp_out_ch_slice > 1024) ? 1024 : tp_out_ch_slice) < 128) ? ((tp_out_ch_slice > 1024) ? 1024 : tp_out_ch_slice) : 128);
  int CHout_Split_Times = ((out_ch_slice < 128) ? (((128 + out_ch_slice) - 1) / out_ch_slice) : 1);
  int out_ch_slice_last = ((128 % out_ch_slice) ? (128 % out_ch_slice) : out_ch_slice);
  int total_clks_if_reuse_wt = ((((((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 8192) * token) * ((CHout_Split_Times - 1) + 1)) / 8192) + ((((128 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16) / 8) / 8192)) + 20);
  int total_clks_if_reuse_dat = (((((((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512) * 8192) * token) / 8192) + (((((128 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16) / 8) * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int h = 0; h < 8; h += 1) {
      for (int ch = 0; ch < ((CHout_Split_Times - 1) + 1); ch += 1) {
        for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
          uint64_t feature_in_addr = ((runtime2 + (32 * (w * out_w_slice))) + (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          uint64_t wt_base_addr = ((hbm_cache1 + (((4096 * ch) * out_ch_slice) / 32)) + (h * 16384));
          uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((h * (32 * token)) / 1));
          CSB_Write(device, 2, (((((token + last_token) + 32) - 1) / 32) * 32));
          CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 4, 1);
          CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 6, 1);
          CSB_Write(device, 7, ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          CSB_Write(device, 8, (ch * out_ch_slice));
          CSB_Write(device, 9, 128);
          CSB_Write(device, 10, ((uint32_t)feature_in_addr));
          CSB_Write(device, 11, ((uint32_t)wt_base_addr));
          CSB_Write(device, 12, (((((128 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16) / 8) / 128) * 8));
          CSB_Write(device, 13, ((uint32_t)feature_out_addr));
          CSB_Write(device, 14, 0);
          CSB_Write(device, 15, 0);
          CSB_Write(device, 16, (w ? 1 : 0));
          CSB_Write(device, 17, 4);
          CSB_Write(device, 18, 224577);
          CSB_Write(device, 19, 65792);
          CSB_Write(device, 20, 65792);
          CSB_Write(device, 21, 0);
          CSB_Write(device, 22, 0);
          CSB_Write(device, 23, 0);
          CSB_Write(device, 24, 0);
          CSB_Write(device, 25, 0);
          CSB_Write(device, 26, 4096);
          CSB_Write(device, 27, 260);
          CSB_Write(device, 28, 2);
          CSB_Write(device, 29, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          CSB_Write(device, 30, (32 * token));
          CSB_Write(device, 31, (32 * token));
          CSB_Write(device, 32, (32 * token));
          CSB_Write(device, 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          CSB_Write(device, 34, 15);
#ifdef PRINT_STEP
          printf("start mvm_f16xf16_step_9\n");
#endif
          while (CSB_Read(device, 1) != 1) {}
        }
      }
    }
  } else {
    for (int h = 0; h < 8; h += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        for (int ch = 0; ch < ((CHout_Split_Times - 1) + 1); ch += 1) {
          uint64_t feature_in_addr = ((runtime2 + (32 * (w * out_w_slice))) + (h * ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512))));
          uint64_t wt_base_addr = ((hbm_cache1 + (((4096 * ch) * out_ch_slice) / 32)) + (h * 16384));
          uint64_t feature_out_addr = ((runtime3 + (32 * (w * out_w_slice))) + ((h * (32 * token)) / 1));
          CSB_Write(device, 2, (((((token + last_token) + 32) - 1) / 32) * 32));
          CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 4, 1);
          CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
          CSB_Write(device, 6, 1);
          CSB_Write(device, 7, ((ch < (CHout_Split_Times - 1)) ? out_ch_slice : out_ch_slice_last));
          CSB_Write(device, 8, (ch * out_ch_slice));
          CSB_Write(device, 9, 128);
          CSB_Write(device, 10, ((uint32_t)feature_in_addr));
          CSB_Write(device, 11, ((uint32_t)wt_base_addr));
          CSB_Write(device, 12, (((((128 * (((((((((token + last_token) + 32) - 1) / 32) * 32) + 32) - 1) / 32) * 32)) * 16) / 8) / 128) * 8));
          CSB_Write(device, 13, ((uint32_t)feature_out_addr));
          CSB_Write(device, 14, 0);
          CSB_Write(device, 15, 0);
          CSB_Write(device, 16, ((ch ? 1 : 0) * 2));
          CSB_Write(device, 17, 4);
          CSB_Write(device, 18, 224577);
          CSB_Write(device, 19, 65792);
          CSB_Write(device, 20, 65792);
          CSB_Write(device, 21, 0);
          CSB_Write(device, 22, 0);
          CSB_Write(device, 23, 0);
          CSB_Write(device, 24, 0);
          CSB_Write(device, 25, 0);
          CSB_Write(device, 26, 4096);
          CSB_Write(device, 27, 260);
          CSB_Write(device, 28, 2);
          CSB_Write(device, 29, ((32 * token) * ((((((((token + last_token) + 32) - 1) / 32) * 32) + 512) - 1) / 512)));
          CSB_Write(device, 30, (32 * token));
          CSB_Write(device, 31, (32 * token));
          CSB_Write(device, 32, (32 * token));
          CSB_Write(device, 33, ((uint32_t)((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16))));
          CSB_Write(device, 34, 15);
#ifdef PRINT_STEP
          printf("start mvm_f16xf16_step_9\n");
#endif
          while (CSB_Read(device, 1) != 1) {}
        }
      }
    }
  }
}
void mvm_f16xi4_step_10(HANDLE& device, int token) {
  int min_dat_depth = (((token * 4096) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 128;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = (((((4096 * token) * 16) / 8192) + 132) + 20);
  int total_clks_if_reuse_dat = (((((4096 * token) * 16) / 8192) + ((1081344 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 1; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime3 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm7 + (33792 * ch));
        uint64_t feature_out_addr = ((runtime1 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm8 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 4096);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 16896);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 2048);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_10\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 1; ch += 1) {
        uint64_t feature_in_addr = (runtime3 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm7 + (33792 * ch));
        uint64_t feature_out_addr = ((runtime1 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm8 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 4096);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 16896);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 2048);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_10\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void elementwise_step_11(HANDLE& device, int token) {
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  for (int w = 0; w < 1; w += 1) {
    uint64_t feature_in_addr = (runtime1 + ((w * out_w_per_slice) * 32));
    uint64_t wt_base_addr = (runtime0 + ((w * out_w_per_slice) * 32));
    uint64_t feature_out_addr = (runtime3 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, 0);
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, (32 * token));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, (32 * token));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, 512);
    CSB_Write(device, 138, ((w < 0) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 139, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 140, ((uint32_t)wt_base_addr));
    CSB_Write(device, 141, (32 * token));
    CSB_Write(device, 142, (32 * token));
    CSB_Write(device, 145, 2);
#ifdef PRINT_STEP
    printf("start elementwise_step_11\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void norm_step_12(HANDLE& device, int token) {
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  for (int w = 0; w < 1; w += 1) {
    uint64_t feature_in_addr = (runtime3 + ((w * out_w_per_slice) * 32));
    uint64_t wt_base_addr = hbm9;
    uint64_t feature_out_addr = (runtime0 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, ((uint32_t)wt_base_addr));
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, (32 * token));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, (32 * token));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, 512);
    CSB_Write(device, 138, 1);
    CSB_Write(device, 139, ((w < 0) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 140, 1);
    CSB_Write(device, 141, 180224);
    CSB_Write(device, 142, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 143, 65793);
    CSB_Write(device, 144, 0);
    CSB_Write(device, 145, 32);
#ifdef PRINT_STEP
    printf("start norm_step_12\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void mvm_f16xi4_step_13(HANDLE& device, int token) {
  int min_dat_depth = (((token * 512) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 1024;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = ((((((512 * token) * 2) * 16) / 8192) + 72) + 20);
  int total_clks_if_reuse_dat = (((((512 * token) * 16) / 8192) + ((589824 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 2; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime0 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm10 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime2 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm11 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 1) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_13\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 2; ch += 1) {
        uint64_t feature_in_addr = (runtime0 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm10 + (9216 * ch));
        uint64_t feature_out_addr = ((runtime2 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 1024) / 512)));
        uint64_t BN_base_addr = (hbm11 + (32 * ((ch * 1024) / 256)));
        CSB_Write(device, 2, 512);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 1) ? 1024 : 1024));
        CSB_Write(device, 8, (ch * 1024));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 2304);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 512);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_13\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void activate_step_14(HANDLE& device, int token) {
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  for (int w = 0; w < 1; w += 1) {
    uint64_t feature_in_addr = (runtime2 + ((w * out_w_per_slice) * 32));
    uint64_t wt_base_addr = hbm12;
    uint64_t feature_out_addr = (runtime0 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, ((uint32_t)wt_base_addr));
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, (32 * token));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, (32 * token));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, 2048);
    CSB_Write(device, 138, 1);
    CSB_Write(device, 139, ((w < 0) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 140, (w ? 2 : 1));
    CSB_Write(device, 141, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 142, 0);
    CSB_Write(device, 143, 0);
    CSB_Write(device, 144, 0);
    CSB_Write(device, 145, 16);
#ifdef PRINT_STEP
    printf("start activate_step_14\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}
void mvm_f16xi4_step_15(HANDLE& device, int token) {
  int min_dat_depth = (((token * 2048) * 16) / 8192);
  int Wout_Split_Times_minus1 = 0;
  int out_w_slice = token;
  int out_w_slice_last = token;
  if ((min_dat_depth > 1024)) {
    out_w_slice = 256;
    out_w_slice_last = ((token % out_w_slice) ? (token % out_w_slice) : out_w_slice);
    Wout_Split_Times_minus1 = ((((token + out_w_slice) - 1) / out_w_slice) - 1);
  }
  int total_clks_if_reuse_wt = (((((2048 * token) * 16) / 8192) + 66) + 20);
  int total_clks_if_reuse_dat = (((((2048 * token) * 16) / 8192) + ((540672 * (Wout_Split_Times_minus1 + 1)) / 8192)) + 20);
  if ((total_clks_if_reuse_wt < total_clks_if_reuse_dat)) {
    for (int ch = 0; ch < 1; ch += 1) {
      for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
        uint64_t feature_in_addr = (runtime0 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm13 + (16896 * ch));
        uint64_t feature_out_addr = ((runtime1 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm14 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 2048);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 8448);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, ((w ? 1 : 0) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 2048);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_15\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  } else {
    for (int w = 0; w < (Wout_Split_Times_minus1 + 1); w += 1) {
      for (int ch = 0; ch < 1; ch += 1) {
        uint64_t feature_in_addr = (runtime0 + (32 * (w * out_w_slice)));
        uint64_t wt_base_addr = (hbm13 + (16896 * ch));
        uint64_t feature_out_addr = ((runtime1 + (32 * (w * out_w_slice))) + ((32 * token) * ((ch * 512) / 512)));
        uint64_t BN_base_addr = (hbm14 + (32 * ((ch * 512) / 256)));
        CSB_Write(device, 2, 2048);
        CSB_Write(device, 3, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 4, 1);
        CSB_Write(device, 5, ((w < Wout_Split_Times_minus1) ? out_w_slice : out_w_slice_last));
        CSB_Write(device, 6, 1);
        CSB_Write(device, 7, ((ch < 0) ? 512 : 512));
        CSB_Write(device, 8, (ch * 512));
        CSB_Write(device, 9, 0);
        CSB_Write(device, 10, ((uint32_t)feature_in_addr));
        CSB_Write(device, 11, ((uint32_t)wt_base_addr));
        CSB_Write(device, 12, 8448);
        CSB_Write(device, 13, ((uint32_t)feature_out_addr));
        CSB_Write(device, 14, 0);
        CSB_Write(device, 15, 0);
        CSB_Write(device, 16, (((ch ? 1 : 0) * 2) + 4));
        CSB_Write(device, 17, 1);
        CSB_Write(device, 18, 0);
        CSB_Write(device, 19, 65792);
        CSB_Write(device, 20, 65792);
        CSB_Write(device, 21, 0);
        CSB_Write(device, 22, 11536384);
        CSB_Write(device, 23, 7340160);
        CSB_Write(device, 24, 2048);
        CSB_Write(device, 25, ((uint32_t)BN_base_addr));
        CSB_Write(device, 26, 0);
        CSB_Write(device, 27, 0);
        CSB_Write(device, 28, 0);
        CSB_Write(device, 29, (32 * token));
        CSB_Write(device, 30, (32 * token));
        CSB_Write(device, 31, (32 * token));
        CSB_Write(device, 32, (32 * token));
        CSB_Write(device, 33, ((uint32_t)(((BN_base_addr & 1095216660480) >> 8) + ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)))));
        CSB_Write(device, 34, 31);
#ifdef PRINT_STEP
        printf("start mvm_f16xi4_step_15\n");
#endif
        while (CSB_Read(device, 1) != 1) {}
      }
    }
  }
}
void elementwise_step_16(HANDLE& device, int token) {
  int out_w_per_slice = token;
  int out_w_in_last_slice = token;
  for (int w = 0; w < 1; w += 1) {
    uint64_t feature_in_addr = (runtime3 + ((w * out_w_per_slice) * 32));
    uint64_t wt_base_addr = (runtime1 + ((w * out_w_per_slice) * 32));
    uint64_t feature_out_addr = (runtime0 + ((w * out_w_per_slice) * 32));
    CSB_Write(device, 130, 0);
    CSB_Write(device, 131, ((uint32_t)feature_in_addr));
    CSB_Write(device, 132, (32 * token));
    CSB_Write(device, 133, (32 * token));
    CSB_Write(device, 134, ((uint32_t)feature_out_addr));
    CSB_Write(device, 135, (32 * token));
    CSB_Write(device, 136, (32 * token));
    CSB_Write(device, 137, 512);
    CSB_Write(device, 138, ((w < 0) ? out_w_per_slice : out_w_in_last_slice));
    CSB_Write(device, 139, ((((feature_in_addr & 1095216660480) >> 32) + ((feature_out_addr & 1095216660480) >> 24)) + ((wt_base_addr & 1095216660480) >> 16)));
    CSB_Write(device, 140, ((uint32_t)wt_base_addr));
    CSB_Write(device, 141, (32 * token));
    CSB_Write(device, 142, (32 * token));
    CSB_Write(device, 145, 2);
#ifdef PRINT_STEP
    printf("start elementwise_step_16\n");
#endif
    while (CSB_Read(device, 129) != 1) {}
  }
}

void test(HANDLE& device, int token, int last_token) {
  norm_step_1(device, token);
  mvm_f16xi4_step_2(device, token);
  mvm_f16xi4_step_3(device, token);
  kvcache2hbm_step_4(device, token, last_token);
  mvm_f16xf16_step_5(device, token, last_token);
  softmax_step_6(device, token, last_token);
  mvm_f16xi4_step_7(device, token);
  kvcache2hbm_step_8(device, token, last_token);
  mvm_f16xf16_step_9(device, token, last_token);
  mvm_f16xi4_step_10(device, token);
  elementwise_step_11(device, token);
  norm_step_12(device, token);
  mvm_f16xi4_step_13(device, token);
  activate_step_14(device, token);
  mvm_f16xi4_step_15(device, token);
  elementwise_step_16(device, token);
}
