// generated by codegen c++ test ops head at 2024-07-30 06:14:32
#ifdef REGS_DEBUG
FILE* LOG;
#endif
// global storage define
uint64_t global0 = 0x200000000; // storage size: 131072 B
uint64_t global1 = 0x200020000; // storage size: 8192 B
// weight storage define
uint64_t weight0 = 0x200022000; // storage size: 16384 B
uint64_t weight1 = 0x200026000; // storage size: 17408 B
uint64_t weight2 = 0x20002a400; // storage size: 1024 B
uint64_t weight3 = 0x20002a800; // storage size: 16384 B
uint64_t weight4 = 0x20002e800; // storage size: 16384 B
uint64_t weight5 = 0x200032800; // storage size: 54784 B
uint64_t weight6 = 0x20003fe00; // storage size: 54784 B
uint64_t weight7 = 0x20004d400; // storage size: 16384 B
uint64_t weight8 = 0x200051400; // storage size: 16384 B
uint64_t weight9 = 0x200055400; // storage size: 260096 B
// cache storage define
uint64_t cache0 = 0x200094c00; // storage size: 262144 B
uint64_t cache1 = 0x2000d4c00; // storage size: 262144 B
// runtime storage define
uint64_t runtime0 = 0x200114c00; // storage size: 4194304 B
uint64_t runtime1 = 0x200514c00; // storage size: 14024704 B
uint64_t runtime2 = 0x201274c00; // storage size: 16777216 B
uint64_t runtime3 = 0x202274c00; // storage size: 66584576 B
// hbm storage define
uint64_t hbm0 = 0x000000000; // storage size: 287232 B
uint64_t hbm1 = 0x000046200; // storage size: 16896 B
uint64_t hbm2 = 0x00004a400; // storage size: 270336 B
uint64_t hbm3 = 0x00008c400; // storage size: 903936 B
uint64_t hbm4 = 0x000168f00; // storage size: 903936 B
uint64_t hbm5 = 0x000245a00; // storage size: 905216 B
uint64_t hbm6 = 0x000322a00; // storage size: 4291584 B

// get input ptr
uint64_t data_in = 0x200114c00; // 1133568

// get output ptr
uint64_t data_out = 0x200114c00; // 1133568

// get weight ddr ptr
uint64_t BLOCK00_ln_k_bias = 0x200022000; // 139264
uint64_t BLOCK00_q_bn_bias = 0x200026000; // 155648
uint64_t pos_emb = 0x200000000; // 0
uint64_t BLOCK00_v_bn_bias = 0x20002a400; // 173056
uint64_t BLOCK00_atten_bn = 0x20002a800; // 174080
uint64_t BLOCK00_post_k_bias = 0x20002e800; // 190464
uint64_t BLOCK00_h_to_4h_bn_1 = 0x200032800; // 206848
uint64_t BLOCK00_h_to_4h_bn_0 = 0x20003fe00; // 261632
uint64_t silu_act = 0x200020000; // 131072
uint64_t BLOCK00_dense_4h_to_h_bn = 0x20004d400; // 316416
uint64_t Final_LN_k_bias = 0x200051400; // 332800
uint64_t Output_Layer_bn = 0x200055400; // 349184

// get weight hbm ptr
uint64_t BLOCK00_q_weight = 0x000000000; // 0
uint64_t BLOCK00_v_weight = 0x000046200; // 287232
uint64_t BLOCK00_atten_weight = 0x00004a400; // 304128
uint64_t BLOCK00_h_to_4h_wt_1 = 0x00008c400; // 574464
uint64_t BLOCK00_h_to_4h_wt_0 = 0x000168f00; // 1478400
uint64_t BLOCK00_dense_4h_to_h_wt = 0x000245a00; // 2382336
uint64_t Output_Layer_wt = 0x000322a00; // 3287552

// mod init
void chatglm2_512_clock_0730_0614_load_params(HANDLE device, HANDLE h2cx) {
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/LN_DDR_bin/LN0_wt_in_DDR.bin", 8590073856, 16384);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_00.bin", 0, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_01.bin", 268435456, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_02.bin", 536870912, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_03.bin", 805306368, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_04.bin", 1073741824, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_05.bin", 1342177280, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_06.bin", 1610612736, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_07.bin", 1879048192, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_08.bin", 2147483648, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_09.bin", 2415919104, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_10.bin", 2684354560, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_11.bin", 2952790016, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_12.bin", 3221225472, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_13.bin", 3489660928, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_14.bin", 3758096384, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_15.bin", 4026531840, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_16.bin", 4294967296, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_17.bin", 4563402752, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_18.bin", 4831838208, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_19.bin", 5100273664, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_20.bin", 5368709120, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_21.bin", 5637144576, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_22.bin", 5905580032, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_23.bin", 6174015488, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_24.bin", 6442450944, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_25.bin", 6710886400, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_26.bin", 6979321856, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_27.bin", 7247757312, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_28.bin", 7516192768, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_29.bin", 7784628224, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_30.bin", 8053063680, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_q_HBM_DDR_31.bin", 8321499136, 287232);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_DDR_bin/MVMBN0_q_wt_and_bias_in_DDR.bin", 8590090240, 17408);
  DDR_Write_bin(h2cx, "BLOCK_write_data/pos_in_4_token512_ch32.bin", 8589934592, 131072);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_00.bin", 287232, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_01.bin", 268722688, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_02.bin", 537158144, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_03.bin", 805593600, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_04.bin", 1074029056, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_05.bin", 1342464512, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_06.bin", 1610899968, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_07.bin", 1879335424, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_08.bin", 2147770880, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_09.bin", 2416206336, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_10.bin", 2684641792, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_11.bin", 2953077248, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_12.bin", 3221512704, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_13.bin", 3489948160, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_14.bin", 3758383616, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_15.bin", 4026819072, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_16.bin", 4295254528, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_17.bin", 4563689984, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_18.bin", 4832125440, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_19.bin", 5100560896, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_20.bin", 5368996352, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_21.bin", 5637431808, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_22.bin", 5905867264, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_23.bin", 6174302720, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_24.bin", 6442738176, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_25.bin", 6711173632, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_26.bin", 6979609088, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_27.bin", 7248044544, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_28.bin", 7516480000, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_29.bin", 7784915456, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_30.bin", 8053350912, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN0_v_HBM_DDR_31.bin", 8321786368, 16896);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_DDR_bin/MVMBN0_v_wt_and_bias_in_DDR.bin", 8590107648, 1024);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_00.bin", 304128, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_01.bin", 268739584, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_02.bin", 537175040, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_03.bin", 805610496, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_04.bin", 1074045952, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_05.bin", 1342481408, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_06.bin", 1610916864, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_07.bin", 1879352320, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_08.bin", 2147787776, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_09.bin", 2416223232, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_10.bin", 2684658688, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_11.bin", 2953094144, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_12.bin", 3221529600, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_13.bin", 3489965056, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_14.bin", 3758400512, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_15.bin", 4026835968, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_16.bin", 4295271424, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_17.bin", 4563706880, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_18.bin", 4832142336, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_19.bin", 5100577792, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_20.bin", 5369013248, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_21.bin", 5637448704, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_22.bin", 5905884160, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_23.bin", 6174319616, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_24.bin", 6442755072, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_25.bin", 6711190528, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_26.bin", 6979625984, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_27.bin", 7248061440, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_28.bin", 7516496896, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_29.bin", 7784932352, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_30.bin", 8053367808, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES0_HBM_DDR_31.bin", 8321803264, 270336);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_DDR_bin/MVMBNRES0_wt_and_bias_in_DDR.bin", 8590108672, 16384);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/LN_DDR_bin/LN1_wt_in_DDR.bin", 8590125056, 16384);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_00.bin", 574464, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_01.bin", 269009920, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_02.bin", 537445376, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_03.bin", 805880832, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_04.bin", 1074316288, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_05.bin", 1342751744, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_06.bin", 1611187200, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_07.bin", 1879622656, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_08.bin", 2148058112, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_09.bin", 2416493568, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_10.bin", 2684929024, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_11.bin", 2953364480, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_12.bin", 3221799936, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_13.bin", 3490235392, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_14.bin", 3758670848, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_15.bin", 4027106304, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_16.bin", 4295541760, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_17.bin", 4563977216, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_18.bin", 4832412672, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_19.bin", 5100848128, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_20.bin", 5369283584, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_21.bin", 5637719040, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_22.bin", 5906154496, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_23.bin", 6174589952, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_24.bin", 6443025408, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_25.bin", 6711460864, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_26.bin", 6979896320, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_27.bin", 7248331776, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_28.bin", 7516767232, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_29.bin", 7785202688, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_30.bin", 8053638144, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES1_HBM_DDR_31.bin", 8322073600, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_DDR_bin/MVMBNRES1_wt_and_bias_in_DDR.bin", 8590141440, 54784);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_00.bin", 1478400, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_01.bin", 269913856, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_02.bin", 538349312, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_03.bin", 806784768, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_04.bin", 1075220224, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_05.bin", 1343655680, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_06.bin", 1612091136, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_07.bin", 1880526592, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_08.bin", 2148962048, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_09.bin", 2417397504, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_10.bin", 2685832960, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_11.bin", 2954268416, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_12.bin", 3222703872, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_13.bin", 3491139328, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_14.bin", 3759574784, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_15.bin", 4028010240, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_16.bin", 4296445696, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_17.bin", 4564881152, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_18.bin", 4833316608, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_19.bin", 5101752064, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_20.bin", 5370187520, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_21.bin", 5638622976, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_22.bin", 5907058432, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_23.bin", 6175493888, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_24.bin", 6443929344, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_25.bin", 6712364800, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_26.bin", 6980800256, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_27.bin", 7249235712, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_28.bin", 7517671168, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_29.bin", 7786106624, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_30.bin", 8054542080, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_write_to_HBM_bin/MVMBN1_HBM_DDR_31.bin", 8322977536, 903936);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_DDR_bin/MVMBN1_wt_and_bias_in_DDR.bin", 8590196224, 54784);
  DDR_Write_bin(h2cx, "BLOCK_write_data/ACT_parameter_in_DDR.bin", 8590065664, 8192);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_00.bin", 2382336, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_01.bin", 270817792, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_02.bin", 539253248, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_03.bin", 807688704, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_04.bin", 1076124160, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_05.bin", 1344559616, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_06.bin", 1612995072, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_07.bin", 1881430528, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_08.bin", 2149865984, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_09.bin", 2418301440, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_10.bin", 2686736896, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_11.bin", 2955172352, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_12.bin", 3223607808, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_13.bin", 3492043264, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_14.bin", 3760478720, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_15.bin", 4028914176, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_16.bin", 4297349632, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_17.bin", 4565785088, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_18.bin", 4834220544, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_19.bin", 5102656000, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_20.bin", 5371091456, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_21.bin", 5639526912, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_22.bin", 5907962368, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_23.bin", 6176397824, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_24.bin", 6444833280, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_25.bin", 6713268736, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_26.bin", 6981704192, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_27.bin", 7250139648, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_28.bin", 7518575104, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_29.bin", 7787010560, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_30.bin", 8055446016, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_write_to_HBM_bin/MVMBNRES2_HBM_DDR_31.bin", 8323881472, 905216);
  DDR_Write_bin(h2cx, "BLOCK_write_data/BLOCK00/MVM_BN_RES_DDR_bin/MVMBNRES2_wt_and_bias_in_DDR.bin", 8590251008, 16384);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/LN_DDR_bin/LN_wt_in_DDR.bin", 8590267392, 16384);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_00.bin", 3287552, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_01.bin", 271723008, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_02.bin", 540158464, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_03.bin", 808593920, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_04.bin", 1077029376, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_05.bin", 1345464832, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_06.bin", 1613900288, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_07.bin", 1882335744, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_08.bin", 2150771200, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_09.bin", 2419206656, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_10.bin", 2687642112, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_11.bin", 2956077568, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_12.bin", 3224513024, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_13.bin", 3492948480, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_14.bin", 3761383936, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_15.bin", 4029819392, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_16.bin", 4298254848, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_17.bin", 4566690304, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_18.bin", 4835125760, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_19.bin", 5103561216, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_20.bin", 5371996672, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_21.bin", 5640432128, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_22.bin", 5908867584, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_23.bin", 6177303040, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_24.bin", 6445738496, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_25.bin", 6714173952, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_26.bin", 6982609408, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_27.bin", 7251044864, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_28.bin", 7519480320, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_29.bin", 7787915776, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_30.bin", 8056351232, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_write_to_HBM_bin/MVMBN_Argmax_HBM_DDR_31.bin", 8324786688, 4291584);
  DDR_Write_bin(h2cx, "BLOCK_write_data/OutLayer/MVM_BN_DDR_bin/MVMBN_Argmax_wt_and_bias_in_DDR.bin", 8590283776, 260096);
}

//#define PRINT_STEP

void step1 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.layer_norm accel operator node, storage data in runtime1 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, 139264);
  CSB_Write(device, 195, 1133568);
  CSB_Write(device, 196, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 197, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 198, 5327872);
  CSB_Write(device, 199, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 200, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 201, 128);
  CSB_Write(device, 202, 1);
  CSB_Write(device, 203, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 204, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 205, 155648);
  CSB_Write(device, 206, 8);
  CSB_Write(device, 207, 0);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 32);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step1!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step1,accel.hbm.layer_norm,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step1,accel.hbm.layer_norm,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step2 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.mvm_bn accel operator node, storage data in runtime2 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 256);
  CSB_Write(device, 9, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 10, 5327872);
  CSB_Write(device, 11, 0);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 19352576);
  CSB_Write(device, 14, 4);
  CSB_Write(device, 15, 28);
  CSB_Write(device, 16, 0);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 1);
  CSB_Write(device, 22, 1);
  CSB_Write(device, 23, 1);
  CSB_Write(device, 24, 1);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 155648);
  CSB_Write(device, 27, 0);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 30, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 31, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 32, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 33, 799);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step2!\n");
#endif
  while(CSB_Read(device, 1) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step2,accel.hbm.mvm_bn,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step2,accel.hbm.mvm_bn,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step3 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.pos_emb accel operator node, storage data in runtime3 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, (kvcache ? (0 + ((token - 1) * 64)) : (0 + (last_token * 64))));
  CSB_Write(device, 195, 19352576);
  CSB_Write(device, 196, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * 4));
  CSB_Write(device, 197, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 198, 36129792);
  CSB_Write(device, 199, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * 4));
  CSB_Write(device, 200, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 201, 4);
  CSB_Write(device, 202, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 203, last_token);
  CSB_Write(device, 204, 32);
  CSB_Write(device, 205, 65536);
  CSB_Write(device, 206, 32768);
  CSB_Write(device, 207, 0);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 4);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step3!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step3,accel.hbm.pos_emb,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step3,accel.hbm.pos_emb,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step4 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.pos_emb accel operator node, storage data in cache0 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, (kvcache ? (0 + ((token - 1) * 64)) : (0 + (last_token * 64))));
  CSB_Write(device, 195, 23546880);
  CSB_Write(device, 196, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * 4));
  CSB_Write(device, 197, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 198, (kvcache ? (609280 + ((token - 1) * 64)) : (609280 + (last_token * 64))));
  CSB_Write(device, 199, 131072);
  CSB_Write(device, 200, 32768);
  CSB_Write(device, 201, 4);
  CSB_Write(device, 202, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 203, last_token);
  CSB_Write(device, 204, 2);
  CSB_Write(device, 205, 65536);
  CSB_Write(device, 206, 32768);
  CSB_Write(device, 207, 0);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 4);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step4!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step4,accel.hbm.pos_emb,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step4,accel.hbm.pos_emb,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step5 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.mvm_afterTRP accel operator node, storage data in runtime2 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, 609280);
  CSB_Write(device, 195, 36129792);
  CSB_Write(device, 196, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * 4));
  CSB_Write(device, 197, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 198, 19352576);
  CSB_Write(device, 199, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * (((token + 32) - 1) / 32)));
  CSB_Write(device, 200, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 201, 131072);
  CSB_Write(device, 202, 32768);
  CSB_Write(device, 203, 128);
  CSB_Write(device, 204, token);
  CSB_Write(device, 205, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 206, 11688);
  CSB_Write(device, 207, 991234);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 2);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step5!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step5,accel.hbm.mvm_afterTRP,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step5,accel.hbm.mvm_afterTRP,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step6 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.softmax accel operator node, storage data in runtime3 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, 1);//(1 - kvcache));
  CSB_Write(device, 195, 19352576);
  CSB_Write(device, 196, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * (((token + 32) - 1) / 32)));
  CSB_Write(device, 197, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 198, 36129792);
  CSB_Write(device, 199, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * (((token + 32) - 1) / 32)));
  CSB_Write(device, 200, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 201, (((token + 32) - 1) / 32));
  CSB_Write(device, 202, 32);
  CSB_Write(device, 203, token);
  CSB_Write(device, 204, (token - last_token));//(kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 205, (token - last_token));
  CSB_Write(device, 206, last_token);
  CSB_Write(device, 207, 0);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 8);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step6!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step6,accel.hbm.softmax,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step6,accel.hbm.softmax,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step7 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.mvm_bn accel operator node, storage data in cache1 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 256);
  CSB_Write(device, 8, 256);
  CSB_Write(device, 9, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 10, 5327872);
  CSB_Write(device, 11, 287232);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, (kvcache ? (871424 + ((token - 1) * 64)) : (871424 + (last_token * 64))));
  CSB_Write(device, 14, 0);
  CSB_Write(device, 15, 28);
  CSB_Write(device, 16, 0);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 1);
  CSB_Write(device, 22, 1);
  CSB_Write(device, 23, 1);
  CSB_Write(device, 24, 1);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 173056);
  CSB_Write(device, 27, 0);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 30, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 31, 32768);
  CSB_Write(device, 32, 32768);
  CSB_Write(device, 33, 799);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step7!\n");
#endif
  while(CSB_Read(device, 1) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step7,accel.hbm.mvm_bn,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step7,accel.hbm.mvm_bn,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step8 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.mvm_afterF2W accel operator node, storage data in runtime1 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, 871424);
  CSB_Write(device, 195, 36129792);
  CSB_Write(device, 196, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * (((token + 32) - 1) / 32)));
  CSB_Write(device, 197, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 198, 5327872);
  CSB_Write(device, 199, (((64 * (kvcache ? 1 : (token - last_token))) * 1) * 4));
  CSB_Write(device, 200, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 201, 131072);
  CSB_Write(device, 202, 32768);
  CSB_Write(device, 203, 128);
  CSB_Write(device, 204, token);
  CSB_Write(device, 205, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 206, 15360);
  CSB_Write(device, 207, 991234);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 1);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step8!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step8,accel.hbm.mvm_afterF2W,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step8,accel.hbm.mvm_afterF2W,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step9 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.mvm_bn_res accel operator node, storage data in runtime3 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 1024);
  CSB_Write(device, 9, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 10, 5327872);
  CSB_Write(device, 11, 304128);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 36129792);
  CSB_Write(device, 14, 3);
  CSB_Write(device, 15, 28);
  CSB_Write(device, 16, 0);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 1);
  CSB_Write(device, 22, 1);
  CSB_Write(device, 23, 1);
  CSB_Write(device, 24, 1);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 174080);
  CSB_Write(device, 27, 1133568);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 30, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 31, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 32, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 33, 1823);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step9!\n");
#endif
  while(CSB_Read(device, 1) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step9,accel.hbm.mvm_bn_res,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step9,accel.hbm.mvm_bn_res,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step10 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.layer_norm accel operator node, storage data in runtime0 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, 190464);
  CSB_Write(device, 195, 36129792);
  CSB_Write(device, 196, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 197, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 198, 1133568);
  CSB_Write(device, 199, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 200, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 201, 128);
  CSB_Write(device, 202, 1);
  CSB_Write(device, 203, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 204, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 205, 155648);
  CSB_Write(device, 206, 8);
  CSB_Write(device, 207, 0);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 32);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step10!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step10,accel.hbm.layer_norm,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step10,accel.hbm.layer_norm,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step11 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.mvm_bn accel operator node, storage data in runtime2 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 384);
  CSB_Write(device, 9, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 10, 1133568);
  CSB_Write(device, 11, 1478400);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 19352576);
  CSB_Write(device, 14, 13);
  CSB_Write(device, 15, 28);
  CSB_Write(device, 16, 0);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 1);
  CSB_Write(device, 22, 1);
  CSB_Write(device, 23, 1);
  CSB_Write(device, 24, 1);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 261632);
  CSB_Write(device, 27, 0);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 30, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 31, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 32, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 33, 799);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step11!\n");
#endif
  while(CSB_Read(device, 1) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step11,accel.hbm.mvm_bn,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step11,accel.hbm.mvm_bn,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step12 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.activate accel operator node, storage data in runtime1 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, 131072);
  CSB_Write(device, 195, 19352576);
  CSB_Write(device, 196, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 197, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 198, 5327872);
  CSB_Write(device, 199, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 200, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 201, 428);
  CSB_Write(device, 202, 1);
  CSB_Write(device, 203, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 204, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 205, 428);
  CSB_Write(device, 206, 13696);
  CSB_Write(device, 207, 0);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 16);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step12!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step12,accel.hbm.activate,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step12,accel.hbm.activate,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step13 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.mvm_bn_res accel operator node, storage data in runtime2 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 384);
  CSB_Write(device, 9, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 10, 1133568);
  CSB_Write(device, 11, 574464);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 19352576);
  CSB_Write(device, 14, 13);
  CSB_Write(device, 15, 28);
  CSB_Write(device, 16, 2);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 1);
  CSB_Write(device, 22, 1);
  CSB_Write(device, 23, 1);
  CSB_Write(device, 24, 1);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 206848);
  CSB_Write(device, 27, 5327872);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 30, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 31, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 32, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 33, 1823);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step13!\n");
#endif
  while(CSB_Read(device, 1) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step13,accel.hbm.mvm_bn_res,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step13,accel.hbm.mvm_bn_res,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step14 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.mvm_bn_res accel operator node, storage data in runtime0 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 2, 13696);
  CSB_Write(device, 3, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 288);
  CSB_Write(device, 8, 64);
  CSB_Write(device, 9, (kvcache ? 1 : (token - last_token)));
  CSB_Write(device, 10, 19352576);
  CSB_Write(device, 11, 2382336);
  CSB_Write(device, 12, 56576);
  CSB_Write(device, 13, 1133568);
  CSB_Write(device, 14, 14);
  CSB_Write(device, 15, 28);
  CSB_Write(device, 16, 0);
  CSB_Write(device, 17, 0);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 1);
  CSB_Write(device, 22, 1);
  CSB_Write(device, 23, 1);
  CSB_Write(device, 24, 1);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 316416);
  CSB_Write(device, 27, 36129792);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 30, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 31, ((64 * (kvcache ? 1 : (token - last_token))) * 1));
  CSB_Write(device, 32, (64 * (kvcache ? 1 : (token - last_token))));
  CSB_Write(device, 33, 1823);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step14!\n");
#endif
  while(CSB_Read(device, 1) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step14,accel.hbm.mvm_bn_res,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step14,accel.hbm.mvm_bn_res,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step15 (HANDLE device, int kvcache, int token, int last_token) {
// accel.hbm.layer_norm accel operator node, storage data in runtime1 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 194, 332800);
  CSB_Write(device, 195, ((kvcache ? 0 : 1) ? (1133568 + (((token - last_token) - 1) * 64)) : 1133568));
  CSB_Write(device, 196, ((kvcache ? 0 : 1) ? ((64 * (token - last_token)) * 1) : 64));
  CSB_Write(device, 197, ((kvcache ? 0 : 1) ? (64 * (token - last_token)) : 64));
  CSB_Write(device, 198, 5327872);
  CSB_Write(device, 199, 64);
  CSB_Write(device, 200, 64);
  CSB_Write(device, 201, 128);
  CSB_Write(device, 202, 1);
  CSB_Write(device, 203, 1);
  CSB_Write(device, 204, 1);
  CSB_Write(device, 205, 155648);
  CSB_Write(device, 206, 8);
  CSB_Write(device, 207, 0);
  CSB_Write(device, 208, 0);
  CSB_Write(device, 209, 32);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step15!\n");
#endif
  while(CSB_Read(device, 193) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step15,accel.hbm.layer_norm,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step15,accel.hbm.layer_norm,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}

void step16 (HANDLE device) {
// accel.hbm.mvm_bn accel operator node, storage data in runtime3 with 0 offset
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0 = 0;
double time_sec1 = 0;
QueryPerformanceFrequency(&freq);
for (int i = 0; i < 1000; i++) {
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 2, 4096);
  CSB_Write(device, 3, 1);
  CSB_Write(device, 4, 1);
  CSB_Write(device, 5, 1);
  CSB_Write(device, 6, 1);
  CSB_Write(device, 7, 1024);
  CSB_Write(device, 8, 512);
  CSB_Write(device, 9, 1);
  CSB_Write(device, 10, 5327872);
  CSB_Write(device, 11, 3287552);
  CSB_Write(device, 12, 16896);
  CSB_Write(device, 13, 36129792);
  CSB_Write(device, 14, 63);
  CSB_Write(device, 15, 28);
  CSB_Write(device, 16, 0);
  CSB_Write(device, 17, 1133568);
  CSB_Write(device, 18, 0);
  CSB_Write(device, 19, 0);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 1);
  CSB_Write(device, 22, 1);
  CSB_Write(device, 23, 1);
  CSB_Write(device, 24, 1);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 349184);
  CSB_Write(device, 27, 0);
  CSB_Write(device, 28, 0);
  CSB_Write(device, 29, 64);
  CSB_Write(device, 30, 64);
  CSB_Write(device, 31, 64);
  CSB_Write(device, 32, 64);
  CSB_Write(device, 33, 2847);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
#endif
#ifdef PRINT_STEP
printf("start: step16!\n");
#endif
  while(CSB_Read(device, 40) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 += (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 += (unsigned long long)(stop_run.QuadPart - stop_cfg.QuadPart) / (double)freq.QuadPart;
}
fprintf(LOG, "step16,accel.hbm.mvm_bn,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
printf("step16,accel.hbm.mvm_bn,%f,%f,%f,%f\n", time_sec0, time_sec1, time_sec0/double(1000.0), time_sec1/double(1000.0));
#endif
}


void chatglm2_512_clock_0730_0614(HANDLE device, int token, int kvcache, int last_token) {
  step1(device, kvcache, token, last_token);
  step2(device, kvcache, token, last_token);
  step3(device, kvcache, token, last_token);
  step4(device, kvcache, token, last_token);
  step5(device, kvcache, token, last_token);
  step6(device, kvcache, token, last_token);
  step7(device, kvcache, token, last_token);
  step8(device, kvcache, token, last_token);
  step9(device, kvcache, token, last_token);
  step10(device, kvcache, token, last_token);
  step11(device, kvcache, token, last_token);
  step12(device, kvcache, token, last_token);
  step13(device, kvcache, token, last_token);
  step14(device, kvcache, token, last_token);
  step15(device, kvcache, token, last_token);
  step16(device);
}
